import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Search from './Search'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Search Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>Search</div>
        <div className="flex">
          <div className="mx-auto">
            <Search />
          </div>
        </div>
        <div>{children}</div>
      </body>
    </html>
  )
}
