import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TodosList from './TodosList'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Ansh.DEV</title>
      </head>
      <body>
        <div className='flex'>
          <div className="w-1/2 p-4">
            <TodosList />
          </div>
          <div className="w-1/2 p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );

}
